    - name: Ensure vim, bash-completion, and qemu-guest-agent are installed
      ansible.builtin.package:
        name: vim,bash-completion,qemu-guest-agent
        state: present

    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure nginx is started at boot
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started

    - name: Copy https.conf to nginx configuration directory
      ansible.builtin.copy:
        src: files/https.conf
        dest: /etc/nginx/conf.d/https.conf
        owner: root
        group: root
        mode: "0644"

    - name: Ensure the nginx configuration is updated for example.internal
      ansible.builtin.copy:
        src: files/example.internal.conf
        dest: /etc/nginx/conf.d/example.internal.conf

    - name: Create directory structure for example.internal
      ansible.builtin.file:
        path: /var/www/example.internal/html
        state: directory
        owner: root
        group: root
        mode: "0755"
        recurse: true
        setype: httpd_sys_content_t

    - name: Upload index.html to example.internal
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/example.internal/html/index.html
        owner: root
        group: root
        mode: "0644"
        setype: httpd_sys_content_t
      notify: Reload nginx


    - name: Show IP-adress
      ansible.builtin.debug:
        msg: "The IP-adress is {{ ansible_default_ipv4.address }}"

    - name: Copy jinja template to nginx
      ansible.builtin.template:
        src: templates/example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: root
        group: root
        mode: "0755"

    - name: Create several users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - alovelace
        - aturing
        - edijkstra
        - ghopper

    - name: Add several users to groups. Set password and GECOS name
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "$6$rounds=656000$mysecretsalt$.eNM1ZJfq/ia987d11Zo4PGvKRbL7zwWqsxKBpLGGtTmt8bqmWECBvMYHW8grUoSYqkuFLLQjyWzti3fUvMKy/"
        state: present
        groups: "{{ item.groups }}"
        comment: "{{ item.realname }}"
      loop:
        - { name: alovelace, realname: Ada Lovelace, groups: [wheel, audio, video] }
        - { name: aturing, realname: Alan Turing, groups: tape }
        - { name: edijkstra, realname: Edsger Dijkstra, groups: tcpdump }
        - { name: ghopper, realname: Grace Hoppers, groups: [wheel, audio] }

