---
- name: Uninstall webserver
  hosts: web
  become: true
  tasks:
    - name: Stop and disable nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Ensure nginx is absent
      ansible.builtin.package:
        name: nginx
        state: absent
