---
- name: Configure firewall on webserver
  hosts: web
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Ensure firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow http and https services
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - https

- name: Configure firewall on dbserver
  hosts: db
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Ensure firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow mysql service
      ansible.posix.firewalld:
        service: mysql
        state: enabled
        permanent: true
        immediate: true
